export interface Idea {
    id: string;
    user_id: string;
    title: string;
    slug: string;
    summary: string;
    description: string;
    category: string;
    tags: string[];
    technologies: string[];
    implementation_steps: string[];
    features: string[];
    challenges: string[];
    monetization: string;
    target_audience: string;
    status: string;
    difficulty: string;
    estimated_time: number;
    is_hot: boolean;
    edited: boolean;
    upvotes: number;
    downvotes: number;
    favorites: number;
    comments: number;
    views: number;
    created_at: string;
    updated_at: string;
    published_at: string;
}